export * from "./email-icon";
export * from "./facebook-icon";
export * from "./linkedin-icon";
export * from "./twitter-icon";
export * from "./arrow-up-icon";
// export *  from './mo-ibrahim-foundation-icon';
// export * from "./bmw-icon";
// export * from './samsung-icon';
// export * from './mastercard-foundation-icon';
export * from "./afriyan-icon";
export * from "./global-fund-icon";
export * from "./marimbo-icon";
export * from "./men-engage-africa-icon";
export * from "./dutch-icon";
export * from "./rahu-icon";
export * from "./sauti-media-hub-icon";
export * from "./ssrg-icon";
export * from "./un-foundation-icon";
export * from "./UNFPA-icon";
export * from "./hhh-icon";
